name: Box URLs

# 触发条件: 可以按您的需要调整
on:
  schedule:
    - cron: '0 21 2-30/2 * *' # 每个月的偶数日的 21:00 (UTC)
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-urls:
    runs-on: ubuntu-latest
    steps:
    - name: 读取TV源数据
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.user_godown }}
        ref: publish
        path: code
      
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        pip install requests

    - name: Check URLs and Update JSON
      working-directory: code
      run: python tv/script.py

    - name: Commit and push if changes
      working-directory: code
      run: |
        git config --global user.email " "${{ secrets.GT_EMAIL }}""  # 替换为您的email
        git config --global user.name "${{ secrets.GT_ACTOR }}"          # 替换为您的用户名
        git add -A
        git commit -m "Update valid_links.json file" -a || echo "No changes to commit"
        git push
